application: kujenga-pamoja
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /sounds
  static_dir: sounds
- url: /.*
  script: kujengapamoja.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest