window.Physijs=function(){parseInt(THREE.REVISION,10);var n,q=new THREE.Matrix4,r=!1,y=b,b={},g,l,s,k,t,u,v,h=new THREE.Vector3,x=new THREE.Vector3,m=new THREE.Matrix4,p=new THREE.Quaternion;b.scripts={};g=function(){this._eventListeners={}};g.prototype.addEventListener=function(a,c){this._eventListeners.hasOwnProperty(a)||(this._eventListeners[a]=[]);this._eventListeners[a].push(c)};g.prototype.removeEventListener=function(a,c){var e;return this._eventListeners.hasOwnProperty(a)?0<=(e=this._eventListeners[a].indexOf(c))?
(this._eventListeners[a].splice(e,1),!0):!1:!1};g.prototype.dispatchEvent=function(a){var c,e=Array.prototype.splice.call(arguments,1);if(this._eventListeners.hasOwnProperty(a))for(c=0;c<this._eventListeners[a].length;c++)this._eventListeners[a][c].apply(this,e)};g.make=function(a){a.prototype.addEventListener=g.prototype.addEventListener;a.prototype.removeEventListener=g.prototype.removeEventListener;a.prototype.dispatchEvent=g.prototype.dispatchEvent};l=function(){var a=1;return function(){return a++}}();
s=function(a,c,e,d){return new THREE.Vector3(Math.atan2(2*(a*d-c*e),d*d-a*a-c*c+e*e),Math.asin(2*(a*e+c*d)),Math.atan2(2*(e*d-a*c),d*d+a*a-c*c-e*e))};k=function(a,c){m.identity();c.useQuaternion?m.identity().setRotationFromQuaternion(c.quaternion):m.identity().makeRotationFromEuler(c.rotation);m.getInverse(m);h.copy(a);x.copy(c.position);return h.sub(x).applyMatrix4(m)};b.noConflict=function(){window.Physijs=y;return b};b.createMaterial=function(a,c,e){var d=function(){};d.prototype=a;d=new d;d._physijs=
{id:a.id,friction:void 0===c?0.8:c,restitution:void 0===e?0.2:e};return d};b.PointConstraint=function(a,c,e){void 0===e&&(e=c,c=void 0);this.type="point";this.appliedImpulse=0;this.id=l();this.objecta=a._physijs.id;this.positiona=k(e,a).clone();c&&(this.objectb=c._physijs.id,this.positionb=k(e,c).clone())};b.PointConstraint.prototype.getDefinition=function(){return{type:this.type,id:this.id,objecta:this.objecta,objectb:this.objectb,positiona:this.positiona,positionb:this.positionb}};b.HingeConstraint=
function(a,c,e,d){void 0===d&&(d=e,e=c,c=void 0);this.type="hinge";this.appliedImpulse=0;this.id=l();this.scene=a.parent;this.objecta=a._physijs.id;this.positiona=k(e,a).clone();this.position=e.clone();this.axis=d;c&&(this.objectb=c._physijs.id,this.positionb=k(e,c).clone())};b.HingeConstraint.prototype.getDefinition=function(){return{type:this.type,id:this.id,objecta:this.objecta,objectb:this.objectb,positiona:this.positiona,positionb:this.positionb,axis:this.axis}};b.HingeConstraint.prototype.setLimits=
function(a,c,e,d){this.scene.execute("hinge_setLimits",{constraint:this.id,low:a,high:c,bias_factor:e,relaxation_factor:d})};b.HingeConstraint.prototype.enableAngularMotor=function(a,c){this.scene.execute("hinge_enableAngularMotor",{constraint:this.id,velocity:a,acceleration:c})};b.HingeConstraint.prototype.disableMotor=function(a,c){this.scene.execute("hinge_disableMotor",{constraint:this.id})};b.SliderConstraint=function(a,c,e,d){void 0===d&&(d=e,e=c,c=void 0);this.type="slider";this.appliedImpulse=
0;this.id=l();this.scene=a.parent;this.objecta=a._physijs.id;this.positiona=k(e,a).clone();this.axis=d;c&&(this.objectb=c._physijs.id,this.positionb=k(e,c).clone())};b.SliderConstraint.prototype.getDefinition=function(){return{type:this.type,id:this.id,objecta:this.objecta,objectb:this.objectb,positiona:this.positiona,positionb:this.positionb,axis:this.axis}};b.SliderConstraint.prototype.setLimits=function(a,c,e,d){this.scene.execute("slider_setLimits",{constraint:this.id,lin_lower:a,lin_upper:c,
ang_lower:e,ang_upper:d})};b.SliderConstraint.prototype.setRestitution=function(a,c){this.scene.execute("slider_setRestitution",{constraint:this.id,linear:a,angular:c})};b.SliderConstraint.prototype.enableLinearMotor=function(a,c){this.scene.execute("slider_enableLinearMotor",{constraint:this.id,velocity:a,acceleration:c})};b.SliderConstraint.prototype.disableLinearMotor=function(){this.scene.execute("slider_disableLinearMotor",{constraint:this.id})};b.SliderConstraint.prototype.enableAngularMotor=
function(a,c){this.scene.execute("slider_enableAngularMotor",{constraint:this.id,velocity:a,acceleration:c})};b.SliderConstraint.prototype.disableAngularMotor=function(){this.scene.execute("slider_disableAngularMotor",{constraint:this.id})};b.ConeTwistConstraint=function(a,c,e){if(void 0===e)throw"Both objects must be defined in a ConeTwistConstraint.";this.type="conetwist";this.appliedImpulse=0;this.id=l();this.scene=a.parent;this.objecta=a._physijs.id;this.positiona=k(e,a).clone();this.objectb=
c._physijs.id;this.positionb=k(e,c).clone();this.axisa={x:a.rotation.x,y:a.rotation.y,z:a.rotation.z};this.axisb={x:c.rotation.x,y:c.rotation.y,z:c.rotation.z}};b.ConeTwistConstraint.prototype.getDefinition=function(){return{type:this.type,id:this.id,objecta:this.objecta,objectb:this.objectb,positiona:this.positiona,positionb:this.positionb,axisa:this.axisa,axisb:this.axisb}};b.ConeTwistConstraint.prototype.setLimit=function(a,c,e){this.scene.execute("conetwist_setLimit",{constraint:this.id,x:a,y:c,
z:e})};b.ConeTwistConstraint.prototype.enableMotor=function(){this.scene.execute("conetwist_enableMotor",{constraint:this.id})};b.ConeTwistConstraint.prototype.setMaxMotorImpulse=function(a){this.scene.execute("conetwist_setMaxMotorImpulse",{constraint:this.id,max_impulse:a})};b.ConeTwistConstraint.prototype.setMotorTarget=function(a){if(a instanceof THREE.Vector3)throw"Wait for Three.js r50 to setMotorTarget from Vector3 - use Matrix4 or Quaternion instead";a instanceof THREE.Matrix4&&(a=(new THREE.Quaternion).setFromRotationMatrix(a));
this.scene.execute("conetwist_setMotorTarget",{constraint:this.id,x:a.x,y:a.y,z:a.z,w:a.w})};b.ConeTwistConstraint.prototype.disableMotor=function(){this.scene.execute("conetwist_disableMotor",{constraint:this.id})};b.DOFConstraint=function(a,c,e){void 0===e&&(e=c,c=void 0);this.type="dof";this.appliedImpulse=0;this.id=l();this.scene=a.parent;this.objecta=a._physijs.id;this.positiona=k(e,a).clone();this.axisa={x:a.rotation.x,y:a.rotation.y,z:a.rotation.z};c&&(this.objectb=c._physijs.id,this.positionb=
k(e,c).clone(),this.axisb={x:c.rotation.x,y:c.rotation.y,z:c.rotation.z})};b.DOFConstraint.prototype.getDefinition=function(){return{type:this.type,id:this.id,objecta:this.objecta,objectb:this.objectb,positiona:this.positiona,positionb:this.positionb,axisa:this.axisa,axisb:this.axisb}};b.DOFConstraint.prototype.setLinearLowerLimit=function(a){this.scene.execute("dof_setLinearLowerLimit",{constraint:this.id,x:a.x,y:a.y,z:a.z})};b.DOFConstraint.prototype.setLinearUpperLimit=function(a){this.scene.execute("dof_setLinearUpperLimit",
{constraint:this.id,x:a.x,y:a.y,z:a.z})};b.DOFConstraint.prototype.setAngularLowerLimit=function(a){this.scene.execute("dof_setAngularLowerLimit",{constraint:this.id,x:a.x,y:a.y,z:a.z})};b.DOFConstraint.prototype.setAngularUpperLimit=function(a){this.scene.execute("dof_setAngularUpperLimit",{constraint:this.id,x:a.x,y:a.y,z:a.z})};b.DOFConstraint.prototype.enableAngularMotor=function(a){this.scene.execute("dof_enableAngularMotor",{constraint:this.id,which:a})};b.DOFConstraint.prototype.configureAngularMotor=
function(a,c,e,d,b){this.scene.execute("dof_configureAngularMotor",{constraint:this.id,which:a,low_angle:c,high_angle:e,velocity:d,max_force:b})};b.DOFConstraint.prototype.disableAngularMotor=function(a){this.scene.execute("dof_disableAngularMotor",{constraint:this.id,which:a})};b.Scene=function(a){var c=this;g.call(this);THREE.Scene.call(this);this._worker=new Worker(b.scripts.worker||"physijs_worker.js");this._worker.transferableMessage=this._worker.webkitPostMessage||this._worker.postMessage;this._materials=
{};this._objects={};this._vehicles={};this._constraints={};var e=new ArrayBuffer(1);this._worker.transferableMessage(e,[e]);n=0===e.byteLength;this._worker.onmessage=function(a){a=a.data;a instanceof ArrayBuffer&&1!==a.byteLength&&(a=new Float32Array(a));if(a instanceof Float32Array)switch(a[0]){case 0:c._updateScene(a);break;case 1:c._updateCollisions(a);break;case 2:c._updateVehicles(a);break;case 3:c._updateConstraints(a)}else if(a.cmd)switch(a.cmd){case "objectReady":a=a.params;c._objects[a]&&
c._objects[a].dispatchEvent("ready");break;case "worldReady":c.dispatchEvent("ready");break;case "vehicle":window.test=a;break;default:console.debug("Received: "+a.cmd),console.dir(a.params)}else switch(a[0]){case 0:c._updateScene(a);break;case 1:c._updateCollisions(a);break;case 2:c._updateVehicles(a);break;case 3:c._updateConstraints(a)}};a=a||{};a.ammo=b.scripts.ammo||"ammo.js";a.fixedTimeStep=a.fixedTimeStep||1/60;a.rateLimit=a.rateLimit||!0;this.execute("init",a)};b.Scene.prototype=new THREE.Scene;
b.Scene.prototype.constructor=b.Scene;g.make(b.Scene);b.Scene.prototype._updateScene=function(a){var c=a[1],e,d,b;for(d=0;d<c;d++)b=2+14*d,e=this._objects[a[b]],void 0!==e&&(!1===e.__dirtyPosition&&e.position.set(a[b+1],a[b+2],a[b+3]),!1===e.__dirtyRotation&&(e.useQuaternion?e.quaternion.set(a[b+4],a[b+5],a[b+6],a[b+7]):e.rotation=s(a[b+4],a[b+5],a[b+6],a[b+7])),e._physijs.linearVelocity.set(a[b+8],a[b+9],a[b+10]),e._physijs.angularVelocity.set(a[b+11],a[b+12],a[b+13]));n&&this._worker.transferableMessage(a.buffer,
[a.buffer]);r=!1;this.dispatchEvent("update")};b.Scene.prototype._updateVehicles=function(a){var c,e,b;for(e=0;e<(a.length-1)/9;e++)b=1+9*e,c=this._vehicles[a[b]],void 0!==c&&(c=c.wheels[a[b+1]],c.position.set(a[b+2],a[b+3],a[b+4]),c.useQuaternion?c.quaternion.set(a[b+5],a[b+6],a[b+7],a[b+8]):c.rotation=s(a[b+5],a[b+6],a[b+7],a[b+8]));n&&this._worker.transferableMessage(a.buffer,[a.buffer])};b.Scene.prototype._updateConstraints=function(a){var c,e,b,f;for(b=0;b<(a.length-1)/6;b++)f=1+6*b,c=this._constraints[a[f]],
e=this._objects[a[f+1]],void 0!==c&&void 0!==e&&(h.set(a[f+2],a[f+3],a[f+4]),m.extractRotation(e.matrix),h.applyMatrix4(m),c.positiona.addVectors(e.position,h),c.appliedImpulse=a[f+5]);n&&this._worker.transferableMessage(a.buffer,[a.buffer])};b.Scene.prototype._updateCollisions=function(a){var c,b,d,f={},w=[];for(c=0;c<a[1];c++)b=2+2*c,d=a[b],b=a[b+1],f[d]||(f[d]=[]),f[d].push(b);for(d in this._objects){if(!this._objects.hasOwnProperty(d))return;d=this._objects[d];if(f[d._physijs.id]){for(c=w.length=
0;c<f[d._physijs.id].length;c++)if(b=this._objects[f[d._physijs.id][c]])-1===d._physijs.touches.indexOf(b._physijs.id)&&(d._physijs.touches.push(b._physijs.id),h.subVectors(d.getLinearVelocity(),b.getLinearVelocity()),u=h.clone(),h.subVectors(d.getAngularVelocity(),b.getAngularVelocity()),v=h,d.dispatchEvent("collision",b,u,v),b.dispatchEvent("collision",d,u,v)),w.push(b._physijs.id);for(c=0;c<d._physijs.touches.length;c++)-1===w.indexOf(d._physijs.touches[c])&&d._physijs.touches.splice(c--,1)}else d._physijs.touches.length=
0}for(var g in f)if(f.hasOwnProperty(g)&&f[g])for(c=0;c<f[g].length;c++)f[g][c]&&(f[f[g][c]]=f[f[g][c]]||[],f[f[g][c]].push(g));this.collisions=f;n&&this._worker.transferableMessage(a.buffer,[a.buffer])};b.Scene.prototype.addConstraint=function(a,c){this._constraints[a.id]=a;this.execute("addConstraint",a.getDefinition());if(c){var b;switch(a.type){case "point":b=new THREE.Mesh(new THREE.SphereGeometry(1.5),new THREE.MeshNormalMaterial);b.position.copy(a.positiona);this._objects[a.objecta].add(b);
break;case "hinge":b=new THREE.Mesh(new THREE.SphereGeometry(1.5),new THREE.MeshNormalMaterial);b.position.copy(a.positiona);this._objects[a.objecta].add(b);break;case "slider":b=new THREE.Mesh(new THREE.CubeGeometry(10,1,1),new THREE.MeshNormalMaterial);b.position.copy(a.positiona);b.rotation.set(a.axis.y,a.axis.x,a.axis.z);this._objects[a.objecta].add(b);break;case "conetwist":b=new THREE.Mesh(new THREE.SphereGeometry(1.5),new THREE.MeshNormalMaterial);b.position.copy(a.positiona);this._objects[a.objecta].add(b);
break;case "dof":b=new THREE.Mesh(new THREE.SphereGeometry(1.5),new THREE.MeshNormalMaterial),b.position.copy(a.positiona),this._objects[a.objecta].add(b)}}return a};b.Scene.prototype.removeConstraint=function(a){void 0!==this._constraints[a.id]&&(this.execute("removeConstraint",{id:a.id}),delete this._constraints[a.id])};b.Scene.prototype.execute=function(a,c){this._worker.postMessage({cmd:a,params:c})};t=function(a,c){var b;for(b=0;b<c.children.length;b++)c.children[b]._physijs&&(c.children[b].updateMatrix(),
c.children[b].updateMatrixWorld(),h.getPositionFromMatrix(c.children[b].matrixWorld),p.setFromRotationMatrix(c.children[b].matrixWorld),c.children[b]._physijs.position_offset={x:h.x,y:h.y,z:h.z},c.children[b]._physijs.rotation={x:p.x,y:p.y,z:p.z,w:p.w},a._physijs.children.push(c.children[b]._physijs)),t(a,c.children[b])};b.Scene.prototype.add=function(a){THREE.Mesh.prototype.add.call(this,a);a._physijs&&(a.world=this,a instanceof b.Vehicle?(this.add(a.mesh),this._vehicles[a._physijs.id]=a,this.execute("addVehicle",
a._physijs)):(a.__dirtyPosition=!1,a.__dirtyRotation=!1,this._objects[a._physijs.id]=a,a.children.length&&(a._physijs.children=[],t(a,a)),a.material._physijs&&!this._materials.hasOwnProperty(a.material._physijs.id)&&(this.execute("registerMaterial",a.material._physijs),a._physijs.materialId=a.material._physijs.id),a._physijs.position={x:a.position.x,y:a.position.y,z:a.position.z},a.useQuaternion||(q.identity().makeRotationFromEuler(a.rotation),a.quaternion.setFromRotationMatrix(q)),a._physijs.rotation=
{x:a.quaternion.x,y:a.quaternion.y,z:a.quaternion.z,w:a.quaternion.w},new THREE.Vector3(1,1,1),a._physijs.width&&(a._physijs.width*=a.scale.x),a._physijs.height&&(a._physijs.height*=a.scale.y),a._physijs.depth&&(a._physijs.depth*=a.scale.z),this.execute("addObject",a._physijs)))};b.Scene.prototype.remove=function(a){if(a instanceof b.Vehicle){for(this.execute("removeVehicle",{id:a._physijs.id});a.wheels.length;)this.remove(a.wheels.pop());this.remove(a.mesh);delete this._vehicles[a._physijs.id]}else THREE.Mesh.prototype.remove.call(this,
a),a._physijs&&(delete this._objects[a._physijs.id],this.execute("removeObject",{id:a._physijs.id}))};b.Scene.prototype.setFixedTimeStep=function(a){a&&this.execute("setFixedTimeStep",a)};b.Scene.prototype.setGravity=function(a){a&&this.execute("setGravity",a)};b.Scene.prototype.simulate=function(a,c){var b,d,f;if(r)return!1;r=!0;for(b in this._objects)this._objects.hasOwnProperty(b)&&(d=this._objects[b],d.__dirtyPosition||d.__dirtyRotation)&&(f={id:d._physijs.id},d.__dirtyPosition&&(f.pos={x:d.position.x,
y:d.position.y,z:d.position.z},d.__dirtyPosition=!1),d.__dirtyRotation&&(d.useQuaternion||(q.identity().makeRotationFromEuler(d.rotation),d.quaternion.setFromRotationMatrix(q)),f.quat={x:d.quaternion.x,y:d.quaternion.y,z:d.quaternion.z,w:d.quaternion.w},d.__dirtyRotation=!1),this.execute("updateTransform",f));this.execute("simulate",{timeStep:a,maxSubSteps:c});return!0};b.Mesh=function(a,b,e){a&&(g.call(this),THREE.Mesh.call(this,a,b),a.boundingBox||a.computeBoundingBox(),this._physijs={type:null,
id:l(),mass:e||0,touches:[],linearVelocity:new THREE.Vector3,angularVelocity:new THREE.Vector3})};b.Mesh.prototype=new THREE.Mesh;b.Mesh.prototype.constructor=b.Mesh;g.make(b.Mesh);b.Mesh.prototype.__defineGetter__("mass",function(){return this._physijs.mass});b.Mesh.prototype.__defineSetter__("mass",function(a){this._physijs.mass=a;this.world&&this.world.execute("updateMass",{id:this._physijs.id,mass:a})});b.Mesh.prototype.applyCentralImpulse=function(a){this.world&&this.world.execute("applyCentralImpulse",
{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.applyImpulse=function(a,b){this.world&&this.world.execute("applyImpulse",{id:this._physijs.id,impulse_x:a.x,impulse_y:a.y,impulse_z:a.z,x:b.x,y:b.y,z:b.z})};b.Mesh.prototype.applyCentralForce=function(a){this.world&&this.world.execute("applyCentralForce",{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.applyForce=function(a,b){this.world&&this.world.execute("applyForce",{id:this._physijs.id,force_x:a.x,force_y:a.y,force_z:a.z,x:b.x,
y:b.y,z:b.z})};b.Mesh.prototype.getAngularVelocity=function(){return this._physijs.angularVelocity};b.Mesh.prototype.setAngularVelocity=function(a){this.world&&this.world.execute("setAngularVelocity",{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.getLinearVelocity=function(){return this._physijs.linearVelocity};b.Mesh.prototype.setLinearVelocity=function(a){this.world&&this.world.execute("setLinearVelocity",{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.setAngularFactor=function(a){this.world&&
this.world.execute("setAngularFactor",{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.setLinearFactor=function(a){this.world&&this.world.execute("setLinearFactor",{id:this._physijs.id,x:a.x,y:a.y,z:a.z})};b.Mesh.prototype.setDamping=function(a,b){this.world&&this.world.execute("setDamping",{id:this._physijs.id,linear:a,angular:b})};b.Mesh.prototype.setCcdMotionThreshold=function(a){this.world&&this.world.execute("setCcdMotionThreshold",{id:this._physijs.id,threshold:a})};b.Mesh.prototype.setCcdSweptSphereRadius=
function(a){this.world&&this.world.execute("setCcdSweptSphereRadius",{id:this._physijs.id,radius:a})};b.PlaneMesh=function(a,c,e){var d;b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;this._physijs.type="plane";this._physijs.normal=a.faces[0].normal.clone();this._physijs.mass="undefined"===typeof e?c*d:e};b.PlaneMesh.prototype=new b.Mesh;b.PlaneMesh.prototype.constructor=b.PlaneMesh;b.HeightfieldMesh=
function(a,c,e,d,f){b.Mesh.call(this,a,c,e);this._physijs.type="heightfield";this._physijs.xsize=a.boundingBox.max.x-a.boundingBox.min.x;this._physijs.ysize=a.boundingBox.max.y-a.boundingBox.min.y;this._physijs.xpts="undefined"===typeof d?Math.sqrt(a.vertices.length):d+1;this._physijs.ypts="undefined"===typeof f?Math.sqrt(a.vertices.length):f+1;this._physijs.absMaxHeight=Math.max(a.boundingBox.max.z,Math.abs(a.boundingBox.min.z));c=[];for(f=0;f<a.vertices.length;f++)e=f%this._physijs.xpts,d=Math.round(f/
this._physijs.xpts-f%this._physijs.xpts/this._physijs.xpts),c[f]=a.vertices[e+(this._physijs.ypts-d-1)*this._physijs.ypts].z;this._physijs.points=c};b.HeightfieldMesh.prototype=new b.Mesh;b.HeightfieldMesh.prototype.constructor=b.HeightfieldMesh;b.BoxMesh=function(a,c,e){var d;b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;a=a.boundingBox.max.z-a.boundingBox.min.z;this._physijs.type="box";this._physijs.width=
c;this._physijs.height=d;this._physijs.depth=a;this._physijs.mass="undefined"===typeof e?c*d*a:e};b.BoxMesh.prototype=new b.Mesh;b.BoxMesh.prototype.constructor=b.BoxMesh;b.SphereMesh=function(a,c,e){b.Mesh.call(this,a,c,e);a.boundingSphere||a.computeBoundingSphere();this._physijs.type="sphere";this._physijs.radius=a.boundingSphere.radius;this._physijs.mass="undefined"===typeof e?4/3*Math.PI*Math.pow(this._physijs.radius,3):e};b.SphereMesh.prototype=new b.Mesh;b.SphereMesh.prototype.constructor=b.SphereMesh;
b.CylinderMesh=function(a,c,e){var d;b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;a=a.boundingBox.max.z-a.boundingBox.min.z;this._physijs.type="cylinder";this._physijs.width=c;this._physijs.height=d;this._physijs.depth=a;this._physijs.mass="undefined"===typeof e?c*d*a:e};b.CylinderMesh.prototype=new b.Mesh;b.CylinderMesh.prototype.constructor=b.CylinderMesh;b.CapsuleMesh=function(a,c,e){var d;b.Mesh.call(this,
a,c,e);a.boundingBox||a.computeBoundingBox();c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;a=a.boundingBox.max.z-a.boundingBox.min.z;this._physijs.type="capsule";this._physijs.radius=Math.max(c/2,a/2);this._physijs.height=d;this._physijs.mass="undefined"===typeof e?c*d*a:e};b.CapsuleMesh.prototype=new b.Mesh;b.CapsuleMesh.prototype.constructor=b.CapsuleMesh;b.ConeMesh=function(a,c,e){b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();c=a.boundingBox.max.x-
a.boundingBox.min.x;a=a.boundingBox.max.y-a.boundingBox.min.y;this._physijs.type="cone";this._physijs.radius=c/2;this._physijs.height=a;this._physijs.mass="undefined"===typeof e?c*a:e};b.ConeMesh.prototype=new b.Mesh;b.ConeMesh.prototype.constructor=b.ConeMesh;b.ConcaveMesh=function(a,c,e){var d,f,g=[];b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();d=a.vertices;for(c=0;c<a.faces.length;c++)f=a.faces[c],f instanceof THREE.Face3?g.push([{x:d[f.a].x,y:d[f.a].y,z:d[f.a].z},{x:d[f.b].x,
y:d[f.b].y,z:d[f.b].z},{x:d[f.c].x,y:d[f.c].y,z:d[f.c].z}]):f instanceof THREE.Face4&&(g.push([{x:d[f.a].x,y:d[f.a].y,z:d[f.a].z},{x:d[f.b].x,y:d[f.b].y,z:d[f.b].z},{x:d[f.d].x,y:d[f.d].y,z:d[f.d].z}]),g.push([{x:d[f.b].x,y:d[f.b].y,z:d[f.b].z},{x:d[f.c].x,y:d[f.c].y,z:d[f.c].z},{x:d[f.d].x,y:d[f.d].y,z:d[f.d].z}]));c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;a=a.boundingBox.max.z-a.boundingBox.min.z;this._physijs.type="concave";this._physijs.triangles=g;this._physijs.mass=
"undefined"===typeof e?c*d*a:e};b.ConcaveMesh.prototype=new b.Mesh;b.ConcaveMesh.prototype.constructor=b.ConcaveMesh;b.ConvexMesh=function(a,c,e){var d,f=[];b.Mesh.call(this,a,c,e);a.boundingBox||a.computeBoundingBox();for(c=0;c<a.vertices.length;c++)f.push({x:a.vertices[c].x,y:a.vertices[c].y,z:a.vertices[c].z});c=a.boundingBox.max.x-a.boundingBox.min.x;d=a.boundingBox.max.y-a.boundingBox.min.y;a=a.boundingBox.max.z-a.boundingBox.min.z;this._physijs.type="convex";this._physijs.points=f;this._physijs.mass=
"undefined"===typeof e?c*d*a:e};b.ConvexMesh.prototype=new b.Mesh;b.ConvexMesh.prototype.constructor=b.ConvexMesh;b.Vehicle=function(a,c){c=c||new b.VehicleTuning;this.mesh=a;this.wheels=[];this._physijs={id:l(),rigidBody:a._physijs.id,suspension_stiffness:c.suspension_stiffness,suspension_compression:c.suspension_compression,suspension_damping:c.suspension_damping,max_suspension_travel:c.max_suspension_travel,friction_slip:c.friction_slip,max_suspension_force:c.max_suspension_force}};b.Vehicle.prototype.addWheel=
function(a,b,e,d,f,g,h,k,l){a=new THREE.Mesh(a,b);a.castShadow=a.receiveShadow=!0;a.position.copy(d).multiplyScalar(g/100).add(e);this.world.add(a);this.wheels.push(a);this.world.execute("addWheel",{id:this._physijs.id,connection_point:{x:e.x,y:e.y,z:e.z},wheel_direction:{x:d.x,y:d.y,z:d.z},wheel_axle:{x:f.x,y:f.y,z:f.z},suspension_rest_length:g,wheel_radius:h,is_front_wheel:k,tuning:l})};b.Vehicle.prototype.setSteering=function(a,b){if(void 0!==b&&void 0!==this.wheels[b])this.world.execute("setSteering",
{id:this._physijs.id,wheel:b,steering:a});else if(0<this.wheels.length)for(var e=0;e<this.wheels.length;e++)this.world.execute("setSteering",{id:this._physijs.id,wheel:e,steering:a})};b.Vehicle.prototype.setBrake=function(a,b){if(void 0!==b&&void 0!==this.wheels[b])this.world.execute("setBrake",{id:this._physijs.id,wheel:b,brake:a});else if(0<this.wheels.length)for(var e=0;e<this.wheels.length;e++)this.world.execute("setBrake",{id:this._physijs.id,wheel:e,brake:a})};b.Vehicle.prototype.applyEngineForce=
function(a,b){if(void 0!==b&&void 0!==this.wheels[b])this.world.execute("applyEngineForce",{id:this._physijs.id,wheel:b,force:a});else if(0<this.wheels.length)for(var e=0;e<this.wheels.length;e++)this.world.execute("applyEngineForce",{id:this._physijs.id,wheel:e,force:a})};b.VehicleTuning=function(a,b,e,d,f,g){this.suspension_stiffness=void 0!==a?a:5.88;this.suspension_compression=void 0!==b?b:0.83;this.suspension_damping=void 0!==e?e:0.88;this.max_suspension_travel=void 0!==d?d:500;this.friction_slip=
void 0!==f?f:10.5;this.max_suspension_force=void 0!==g?g:6E3};return b}();
