var transferableMessage=self.webkitPostMessage||self.postMessage,MESSAGE_TYPES={WORLDREPORT:0,COLLISIONREPORT:1,VEHICLEREPORT:2,CONSTRAINTREPORT:3},_object,_vector,_transform,public_functions={},getShapeFromCache,setShapeCache,createShape,reportWorld,reportVehicles,reportCollisions,reportConstraints,fixedTimeStep,rateLimit,last_simulation_time,last_simulation_duration=0,world,transform,_vec3_1,_vec3_2,_vec3_3,_quat,_objects={},_vehicles={},_constraints={},_materials={},_objects_ammo={},_num_objects=
0,_num_wheels=0,_num_constraints=0,_object_shapes={},REPORT_CHUNKSIZE,WORLDREPORT_ITEMSIZE=14,worldreport,COLLISIONREPORT_ITEMSIZE=2,collisionreport,VEHICLEREPORT_ITEMSIZE=9,vehiclereport,CONSTRAINTREPORT_ITEMSIZE=6,constraintreport,ab=new ArrayBuffer(1);transferableMessage(ab,[ab]);var SUPPORT_TRANSFERABLE=0===ab.byteLength;getShapeFromCache=function(a){return void 0!==_object_shapes[a]?_object_shapes[a]:null};setShapeCache=function(a,b){_object_shapes[a]=b};
createShape=function(a){var b,c;_transform.setIdentity();switch(a.type){case "plane":b="plane_"+a.normal.x+"_"+a.normal.y+"_"+a.normal.z;null===(c=getShapeFromCache(b))&&(_vec3_1.setX(a.normal.x),_vec3_1.setY(a.normal.y),_vec3_1.setZ(a.normal.z),c=new Ammo.btStaticPlaneShape(_vec3_1,0),setShapeCache(b,c));break;case "box":b="box_"+a.width+"_"+a.height+"_"+a.depth;null===(c=getShapeFromCache(b))&&(_vec3_1.setX(a.width/2),_vec3_1.setY(a.height/2),_vec3_1.setZ(a.depth/2),c=new Ammo.btBoxShape(_vec3_1),
setShapeCache(b,c));break;case "sphere":b="sphere_"+a.radius;null===(c=getShapeFromCache(b))&&(c=new Ammo.btSphereShape(a.radius),setShapeCache(b,c));break;case "cylinder":b="cylinder_"+a.width+"_"+a.height+"_"+a.depth;null===(c=getShapeFromCache(b))&&(_vec3_1.setX(a.width/2),_vec3_1.setY(a.height/2),_vec3_1.setZ(a.depth/2),c=new Ammo.btCylinderShape(_vec3_1),setShapeCache(b,c));break;case "capsule":b="capsule_"+a.radius+"_"+a.height;null===(c=getShapeFromCache(b))&&(c=new Ammo.btCapsuleShape(a.radius,
a.height-2*a.radius),setShapeCache(b,c));break;case "cone":b="cone_"+a.radius+"_"+a.height;null===(c=getShapeFromCache(b))&&(c=new Ammo.btConeShape(a.radius,a.height),setShapeCache(b,c));break;case "concave":var d=new Ammo.btTriangleMesh;if(!a.triangles.length)return!1;for(b=0;b<a.triangles.length;b++)c=a.triangles[b],_vec3_1.setX(c[0].x),_vec3_1.setY(c[0].y),_vec3_1.setZ(c[0].z),_vec3_2.setX(c[1].x),_vec3_2.setY(c[1].y),_vec3_2.setZ(c[1].z),_vec3_3.setX(c[2].x),_vec3_3.setY(c[2].y),_vec3_3.setZ(c[2].z),
d.addTriangle(_vec3_1,_vec3_2,_vec3_3,!0);c=new Ammo.btBvhTriangleMeshShape(d,!0,!0);break;case "convex":c=new Ammo.btConvexHullShape;for(b=0;b<a.points.length;b++)d=a.points[b],_vec3_1.setX(d.x),_vec3_1.setY(d.y),_vec3_1.setZ(d.z),c.addPoint(_vec3_1);break;case "heightfield":b=Ammo.allocate(4*a.xpts*a.ypts,"float",Ammo.ALLOC_NORMAL);for(c=0;c<a.points.length;c++)Ammo.setValue(b+c,a.points[c],"float");c=new Ammo.btHeightfieldTerrainShape(a.xpts,a.ypts,b,1,-a.absMaxHeight,a.absMaxHeight,2,0,!1);_vec3_1.setX(a.xsize/
(a.xpts-1));_vec3_1.setY(a.ysize/(a.ypts-1));_vec3_1.setZ(1);c.setLocalScaling(_vec3_1);break;default:return}return c};
public_functions.init=function(a){importScripts(a.ammo);_transform=new Ammo.btTransform;_vec3_1=new Ammo.btVector3(0,0,0);_vec3_2=new Ammo.btVector3(0,0,0);_vec3_3=new Ammo.btVector3(0,0,0);_quat=new Ammo.btQuaternion(0,0,0,0);REPORT_CHUNKSIZE=a.reportsize||50;SUPPORT_TRANSFERABLE?(worldreport=new Float32Array(2+REPORT_CHUNKSIZE*WORLDREPORT_ITEMSIZE),collisionreport=new Float32Array(2+REPORT_CHUNKSIZE*COLLISIONREPORT_ITEMSIZE),vehiclereport=new Float32Array(2+REPORT_CHUNKSIZE*VEHICLEREPORT_ITEMSIZE),
constraintreport=new Float32Array(2+REPORT_CHUNKSIZE*CONSTRAINTREPORT_ITEMSIZE)):(worldreport=[],collisionreport=[],vehiclereport=[],constraintreport=[]);worldreport[0]=MESSAGE_TYPES.WORLDREPORT;collisionreport[0]=MESSAGE_TYPES.COLLISIONREPORT;vehiclereport[0]=MESSAGE_TYPES.VEHICLEREPORT;constraintreport[0]=MESSAGE_TYPES.CONSTRAINTREPORT;var b=new Ammo.btDefaultCollisionConfiguration,c=new Ammo.btCollisionDispatcher(b),d=new Ammo.btSequentialImpulseConstraintSolver,e;a.broadphase||(a.broadphase={type:"dynamic"});
switch(a.broadphase.type){case "sweepprune":_vec3_1.setX(a.broadphase.aabbmin.x);_vec3_1.setY(a.broadphase.aabbmin.y);_vec3_1.setZ(a.broadphase.aabbmin.z);_vec3_2.setX(a.broadphase.aabbmax.x);_vec3_2.setY(a.broadphase.aabbmax.y);_vec3_2.setZ(a.broadphase.aabbmax.z);e=new Ammo.btAxisSweep3(_vec3_1,_vec3_2);break;default:e=new Ammo.btDbvtBroadphase}world=new Ammo.btDiscreteDynamicsWorld(c,e,d,b);fixedTimeStep=a.fixedTimeStep;rateLimit=a.rateLimit;transferableMessage({cmd:"worldReady"})};
public_functions.registerMaterial=function(a){_materials[a.id]=a};public_functions.setFixedTimeStep=function(a){fixedTimeStep=a};public_functions.setGravity=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);world.setGravity(_vec3_1)};
public_functions.addObject=function(a){var b,c;if(c=createShape(a)){if(a.children){var d=new Ammo.btCompoundShape;d.addChildShape(_transform,c);for(b=0;b<a.children.length;b++){c=a.children[b];var e=new Ammo.btTransform;e.setIdentity();_vec3_1.setX(c.position_offset.x);_vec3_1.setY(c.position_offset.y);_vec3_1.setZ(c.position_offset.z);e.setOrigin(_vec3_1);_quat.setX(c.rotation.x);_quat.setY(c.rotation.y);_quat.setZ(c.rotation.z);_quat.setW(c.rotation.w);e.setRotation(_quat);c=createShape(a.children[b]);
d.addChildShape(e,c);Ammo.destroy(e)}c=d}_vec3_1.setX(0);_vec3_1.setY(0);_vec3_1.setZ(0);c.calculateLocalInertia(a.mass,_vec3_1);_transform.setIdentity();_vec3_2.setX(a.position.x);_vec3_2.setY(a.position.y);_vec3_2.setZ(a.position.z);_transform.setOrigin(_vec3_2);_quat.setX(a.rotation.x);_quat.setY(a.rotation.y);_quat.setZ(a.rotation.z);_quat.setW(a.rotation.w);_transform.setRotation(_quat);b=new Ammo.btDefaultMotionState(_transform);b=new Ammo.btRigidBodyConstructionInfo(a.mass,b,c,_vec3_1);void 0!==
a.materialId&&(b.set_m_friction(_materials[a.materialId].friction),b.set_m_restitution(_materials[a.materialId].restitution));b=new Ammo.btRigidBody(b);"undefined"!==typeof a.collision_flags&&b.setCollisionFlags(a.collision_flags);world.addRigidBody(b);b.id=a.id;_objects[b.id]=b;_objects_ammo[void 0!=b.a?b.a:b.ptr]=b.id;_num_objects++;transferableMessage({cmd:"objectReady",params:b.id})}};
public_functions.addVehicle=function(a){var b=new Ammo.btVehicleTuning,c;b.set_m_suspensionStiffness(a.suspension_stiffness);b.set_m_suspensionCompression(a.suspension_compression);b.set_m_suspensionDamping(a.suspension_damping);b.set_m_maxSuspensionTravelCm(a.max_suspension_travel);b.set_m_maxSuspensionForce(a.max_suspension_force);c=new Ammo.btRaycastVehicle(b,_objects[a.rigidBody],new Ammo.btDefaultVehicleRaycaster(world));c.tuning=b;_objects[a.rigidBody].setActivationState(4);c.setCoordinateSystem(0,
1,2);world.addVehicle(c);_vehicles[a.id]=c};public_functions.removeVehicle=function(a){delete _vehicles[a.id]};
public_functions.addWheel=function(a){if(void 0!==_vehicles[a.id]){var b=_vehicles[a.id].tuning;void 0!==a.tuning&&(b=new Ammo.btVehicleTuning,b.set_m_suspensionStiffness(a.tuning.suspension_stiffness),b.set_m_suspensionCompression(a.tuning.suspension_compression),b.set_m_suspensionDamping(a.tuning.suspension_damping),b.set_m_maxSuspensionTravelCm(a.tuning.max_suspension_travel),b.set_m_maxSuspensionForce(a.tuning.max_suspension_force));_vec3_1.setX(a.connection_point.x);_vec3_1.setY(a.connection_point.y);
_vec3_1.setZ(a.connection_point.z);_vec3_2.setX(a.wheel_direction.x);_vec3_2.setY(a.wheel_direction.y);_vec3_2.setZ(a.wheel_direction.z);_vec3_3.setX(a.wheel_axle.x);_vec3_3.setY(a.wheel_axle.y);_vec3_3.setZ(a.wheel_axle.z);_vehicles[a.id].addWheel(_vec3_1,_vec3_2,_vec3_3,a.suspension_rest_length,a.wheel_radius,b,a.is_front_wheel)}_num_wheels++;SUPPORT_TRANSFERABLE?(vehiclereport=new Float32Array(1+_num_wheels*VEHICLEREPORT_ITEMSIZE),vehiclereport[0]=MESSAGE_TYPES.VEHICLEREPORT):vehiclereport=[MESSAGE_TYPES.VEHICLEREPORT]};
public_functions.setSteering=function(a){void 0!==_vehicles[a.id]&&_vehicles[a.id].setSteeringValue(a.steering,a.wheel)};public_functions.setBrake=function(a){void 0!==_vehicles[a.id]&&_vehicles[a.id].setBrake(a.brake,a.wheel)};public_functions.applyEngineForce=function(a){void 0!==_vehicles[a.id]&&_vehicles[a.id].applyEngineForce(a.force,a.wheel)};public_functions.removeObject=function(a){world.removeRigidBody(_objects[a.id]);delete _objects[a.id];_num_objects--};
public_functions.updateTransform=function(a){_object=_objects[a.id];_object.getMotionState().getWorldTransform(_transform);a.pos&&(_vec3_1.setX(a.pos.x),_vec3_1.setY(a.pos.y),_vec3_1.setZ(a.pos.z),_transform.setOrigin(_vec3_1));a.quat&&(_quat.setX(a.quat.x),_quat.setY(a.quat.y),_quat.setZ(a.quat.z),_quat.setW(a.quat.w),_transform.setRotation(_quat));_object.setWorldTransform(_transform);_object.activate()};
public_functions.updateMass=function(a){_object=_objects[a.id];world.removeRigidBody(_object);_vec3_1.setX(0);_vec3_1.setY(0);_vec3_1.setZ(0);_object.setMassProps(a.mass,_vec3_1);world.addRigidBody(_object);_object.activate()};public_functions.applyCentralImpulse=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].applyCentralImpulse(_vec3_1);_objects[a.id].activate()};
public_functions.applyImpulse=function(a){_vec3_1.setX(a.impulse_x);_vec3_1.setY(a.impulse_y);_vec3_1.setZ(a.impulse_z);_vec3_2.setX(a.x);_vec3_2.setY(a.y);_vec3_2.setZ(a.z);_objects[a.id].applyImpulse(_vec3_1,_vec3_2);_objects[a.id].activate()};public_functions.applyCentralForce=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].applyCentralForce(_vec3_1);_objects[a.id].activate()};
public_functions.applyForce=function(a){_vec3_1.setX(a.impulse_x);_vec3_1.setY(a.impulse_y);_vec3_1.setZ(a.impulse_z);_vec3_2.setX(a.x);_vec3_2.setY(a.y);_vec3_2.setZ(a.z);_objects[a.id].applyForce(_vec3_1,_vec3_2);_objects[a.id].activate()};public_functions.setAngularVelocity=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].setAngularVelocity(_vec3_1);_objects[a.id].activate()};
public_functions.setLinearVelocity=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].setLinearVelocity(_vec3_1);_objects[a.id].activate()};public_functions.setAngularFactor=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].setAngularFactor(_vec3_1)};public_functions.setLinearFactor=function(a){_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);_objects[a.id].setLinearFactor(_vec3_1)};
public_functions.setDamping=function(a){_objects[a.id].setDamping(a.linear,a.angular)};public_functions.setCcdMotionThreshold=function(a){_objects[a.id].setCcdMotionThreshold(a.threshold)};public_functions.setCcdSweptSphereRadius=function(a){_objects[a.id].setCcdSweptSphereRadius(a.radius)};
public_functions.addConstraint=function(a){var b;switch(a.type){case "point":void 0===a.objectb?(_vec3_1.setX(a.positiona.x),_vec3_1.setY(a.positiona.y),_vec3_1.setZ(a.positiona.z),b=new Ammo.btPoint2PointConstraint(_objects[a.objecta],_vec3_1)):(_vec3_1.setX(a.positiona.x),_vec3_1.setY(a.positiona.y),_vec3_1.setZ(a.positiona.z),_vec3_2.setX(a.positionb.x),_vec3_2.setY(a.positionb.y),_vec3_2.setZ(a.positionb.z),b=new Ammo.btPoint2PointConstraint(_objects[a.objecta],_objects[a.objectb],_vec3_1,_vec3_2));
break;case "hinge":void 0===a.objectb?(_vec3_1.setX(a.positiona.x),_vec3_1.setY(a.positiona.y),_vec3_1.setZ(a.positiona.z),_vec3_2.setX(a.axis.x),_vec3_2.setY(a.axis.y),_vec3_2.setZ(a.axis.z),b=new Ammo.btHingeConstraint(_objects[a.objecta],_vec3_1,_vec3_2)):(_vec3_1.setX(a.positiona.x),_vec3_1.setY(a.positiona.y),_vec3_1.setZ(a.positiona.z),_vec3_2.setX(a.positionb.x),_vec3_2.setY(a.positionb.y),_vec3_2.setZ(a.positionb.z),_vec3_3.setX(a.axis.x),_vec3_3.setY(a.axis.y),_vec3_3.setZ(a.axis.z),b=new Ammo.btHingeConstraint(_objects[a.objecta],
_objects[a.objectb],_vec3_1,_vec3_2,_vec3_3,_vec3_3));break;case "slider":var c,d;c=new Ammo.btTransform;_vec3_1.setX(a.positiona.x);_vec3_1.setY(a.positiona.y);_vec3_1.setZ(a.positiona.z);c.setOrigin(_vec3_1);b=c.getRotation();b.setEuler(a.axis.x,a.axis.y,a.axis.z);c.setRotation(b);a.objectb?(d=new Ammo.btTransform,_vec3_2.setX(a.positionb.x),_vec3_2.setY(a.positionb.y),_vec3_2.setZ(a.positionb.z),d.setOrigin(_vec3_2),b=d.getRotation(),b.setEuler(a.axis.x,a.axis.y,a.axis.z),d.setRotation(b),b=new Ammo.btSliderConstraint(_objects[a.objecta],
_objects[a.objectb],c,d,!0)):b=new Ammo.btSliderConstraint(_objects[a.objecta],c,!0);Ammo.destroy(c);void 0!=d&&Ammo.destroy(d);break;case "conetwist":c=new Ammo.btTransform;c.setIdentity();d=new Ammo.btTransform;d.setIdentity();_vec3_1.setX(a.positiona.x);_vec3_1.setY(a.positiona.y);_vec3_1.setZ(a.positiona.z);_vec3_2.setX(a.positionb.x);_vec3_2.setY(a.positionb.y);_vec3_2.setZ(a.positionb.z);c.setOrigin(_vec3_1);d.setOrigin(_vec3_2);b=c.getRotation();b.setEulerZYX(-a.axisa.z,-a.axisa.y,-a.axisa.x);
c.setRotation(b);b=d.getRotation();b.setEulerZYX(-a.axisb.z,-a.axisb.y,-a.axisb.x);d.setRotation(b);b=new Ammo.btConeTwistConstraint(_objects[a.objecta],_objects[a.objectb],c,d);b.setLimit(Math.PI,0,Math.PI);Ammo.destroy(c);Ammo.destroy(d);break;case "dof":c=new Ammo.btTransform;c.setIdentity();_vec3_1.setX(a.positiona.x);_vec3_1.setY(a.positiona.y);_vec3_1.setZ(a.positiona.z);c.setOrigin(_vec3_1);b=c.getRotation();b.setEulerZYX(-a.axisa.z,-a.axisa.y,-a.axisa.x);c.setRotation(b);a.objectb?(d=new Ammo.btTransform,
d.setIdentity(),_vec3_2.setX(a.positionb.x),_vec3_2.setY(a.positionb.y),_vec3_2.setZ(a.positionb.z),d.setOrigin(_vec3_2),b=d.getRotation(),b.setEulerZYX(-a.axisb.z,-a.axisb.y,-a.axisb.x),d.setRotation(b),b=new Ammo.btGeneric6DofConstraint(_objects[a.objecta],_objects[a.objectb],c,d)):b=new Ammo.btGeneric6DofConstraint(_objects[a.objecta],c);Ammo.destroy(c);void 0!=d&&Ammo.destroy(d);break;default:return}world.addConstraint(b);b.enableFeedback();_constraints[a.id]=b;_num_constraints++;SUPPORT_TRANSFERABLE?
(constraintreport=new Float32Array(1+_num_constraints*CONSTRAINTREPORT_ITEMSIZE),constraintreport[0]=MESSAGE_TYPES.CONSTRAINTREPORT):constraintreport=[MESSAGE_TYPES.CONSTRAINTREPORT]};public_functions.removeConstraint=function(a){var b=_constraints[a.id];void 0!==b&&(world.removeConstraint(b),delete _constraints[a.id],_num_constraints--)};public_functions.constraint_setBreakingImpulseThreshold=function(a){var b=_constraints[a.id];b!==undefind&&b.setBreakingImpulseThreshold(a.threshold)};
public_functions.simulate=function(a){if(world){a=a||{};if(a.timeStep)a.timeStep<fixedTimeStep&&(a.timeStep=fixedTimeStep);else if(last_simulation_time)for(a.timeStep=0;a.timeStep+last_simulation_duration<=fixedTimeStep;)a.timeStep=(Date.now()-last_simulation_time)/1E3;else a.timeStep=fixedTimeStep;a.maxSubSteps=a.maxSubSteps||Math.ceil(a.timeStep/fixedTimeStep);last_simulation_duration=Date.now();world.stepSimulation(a.timeStep,a.maxSubSteps,fixedTimeStep);reportVehicles();reportCollisions();reportConstraints();
reportWorld();last_simulation_duration=(Date.now()-last_simulation_duration)/1E3;last_simulation_time=Date.now()}};public_functions.hinge_setLimits=function(a){_constraints[a.constraint].setLimit(a.low,a.high,0,a.bias_factor,a.relaxation_factor)};public_functions.hinge_enableAngularMotor=function(a){var b=_constraints[a.constraint];b.enableAngularMotor(!0,a.velocity,a.acceleration);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.hinge_disableMotor=function(a){_constraints[a.constraint].enableMotor(!1);constraint.getRigidBodyB()&&constraint.getRigidBodyB().activate()};public_functions.slider_setLimits=function(a){var b=_constraints[a.constraint];b.setLowerLinLimit(a.lin_lower||0);b.setUpperLinLimit(a.lin_upper||0);b.setLowerAngLimit(a.ang_lower||0);b.setUpperAngLimit(a.ang_upper||0)};
public_functions.slider_setRestitution=function(a){var b=_constraints[a.constraint];b.setSoftnessLimLin(a.linear||0);b.setSoftnessLimAng(a.angular||0)};public_functions.slider_enableLinearMotor=function(a){var b=_constraints[a.constraint];b.setTargetLinMotorVelocity(a.velocity);b.setMaxLinMotorForce(a.acceleration);b.setPoweredLinMotor(!0);b.getRigidBodyA().activate();b.getRigidBodyB&&b.getRigidBodyB().activate()};
public_functions.slider_disableLinearMotor=function(a){a=_constraints[a.constraint];a.setPoweredLinMotor(!1);a.getRigidBodyB()&&a.getRigidBodyB().activate()};public_functions.slider_enableAngularMotor=function(a){var b=_constraints[a.constraint];b.setTargetAngMotorVelocity(a.velocity);b.setMaxAngMotorForce(a.acceleration);b.setPoweredAngMotor(!0);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.slider_disableAngularMotor=function(a){a=_constraints[a.constraint];a.setPoweredAngMotor(!1);a.getRigidBodyA().activate();a.getRigidBodyB()&&a.getRigidBodyB().activate()};public_functions.conetwist_setLimit=function(a){_constraints[a.constraint].setLimit(a.z,a.y,a.x)};public_functions.conetwist_enableMotor=function(a){a=_constraints[a.constraint];a.enableMotor(!0);a.getRigidBodyA().activate();a.getRigidBodyB().activate()};
public_functions.conetwist_setMaxMotorImpulse=function(a){var b=_constraints[a.constraint];b.setMaxMotorImpulse(a.max_impulse);b.getRigidBodyA().activate();b.getRigidBodyB().activate()};public_functions.conetwist_setMotorTarget=function(a){var b=_constraints[a.constraint];_quat.setX(a.x);_quat.setY(a.y);_quat.setZ(a.z);_quat.setW(a.w);b.setMotorTarget(_quat);b.getRigidBodyA().activate();b.getRigidBodyB().activate()};
public_functions.conetwist_disableMotor=function(a){a=_constraints[a.constraint];a.enableMotor(!1);a.getRigidBodyA().activate();a.getRigidBodyB().activate()};public_functions.dof_setLinearLowerLimit=function(a){var b=_constraints[a.constraint];_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);b.setLinearLowerLimit(_vec3_1);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.dof_setLinearUpperLimit=function(a){var b=_constraints[a.constraint];_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);b.setLinearUpperLimit(_vec3_1);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};public_functions.dof_setAngularLowerLimit=function(a){var b=_constraints[a.constraint];_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);b.setAngularLowerLimit(_vec3_1);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.dof_setAngularUpperLimit=function(a){var b=_constraints[a.constraint];_vec3_1.setX(a.x);_vec3_1.setY(a.y);_vec3_1.setZ(a.z);b.setAngularUpperLimit(_vec3_1);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};public_functions.dof_enableAngularMotor=function(a){var b=_constraints[a.constraint];b.getRotationalLimitMotor(a.which).set_m_enableMotor(!0);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.dof_configureAngularMotor=function(a){var b=_constraints[a.constraint],c=b.getRotationalLimitMotor(a.which);c.set_m_loLimit(a.low_angle);c.set_m_hiLimit(a.high_angle);c.set_m_targetVelocity(a.velocity);c.set_m_maxMotorForce(a.max_force);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
public_functions.dof_disableAngularMotor=function(a){var b=_constraints[a.constraint];b.getRotationalLimitMotor(a.which).set_m_enableMotor(!1);b.getRigidBodyA().activate();b.getRigidBodyB()&&b.getRigidBodyB().activate()};
reportWorld=function(){var a,b,c,d,e=0,f=0;SUPPORT_TRANSFERABLE&&worldreport.length<2+_num_objects*WORLDREPORT_ITEMSIZE&&(worldreport=new Float32Array(2+Math.ceil(_num_objects/REPORT_CHUNKSIZE)*REPORT_CHUNKSIZE*WORLDREPORT_ITEMSIZE),worldreport[0]=MESSAGE_TYPES.WORLDREPORT);worldreport[1]=_num_objects;for(a in _objects)_objects.hasOwnProperty(a)&&(b=_objects[a],c=b.getCenterOfMassTransform(),d=c.getOrigin(),c=c.getRotation(),e=2+f++*WORLDREPORT_ITEMSIZE,worldreport[e]=b.id,worldreport[e+1]=d.x(),
worldreport[e+2]=d.y(),worldreport[e+3]=d.z(),worldreport[e+4]=c.x(),worldreport[e+5]=c.y(),worldreport[e+6]=c.z(),worldreport[e+7]=c.w(),_vector=b.getLinearVelocity(),worldreport[e+8]=_vector.x(),worldreport[e+9]=_vector.y(),worldreport[e+10]=_vector.z(),_vector=b.getAngularVelocity(),worldreport[e+11]=_vector.x(),worldreport[e+12]=_vector.y(),worldreport[e+13]=_vector.z());SUPPORT_TRANSFERABLE?transferableMessage(worldreport.buffer,[worldreport.buffer]):transferableMessage(worldreport)};
reportCollisions=function(){var a,b,c=world.getDispatcher(),d=c.getNumManifolds(),e;SUPPORT_TRANSFERABLE&&collisionreport.length<2+d*COLLISIONREPORT_ITEMSIZE&&(collisionreport=new Float32Array(2+Math.ceil(_num_objects/REPORT_CHUNKSIZE)*REPORT_CHUNKSIZE*COLLISIONREPORT_ITEMSIZE),collisionreport[0]=MESSAGE_TYPES.COLLISIONREPORT);for(a=collisionreport[1]=0;a<d;a++)if(e=c.getManifoldByIndexInternal(a),b=e.getNumContacts(),0!==b)for(;0<b;){e.getContactPoint(0);b=2+collisionreport[1]++*COLLISIONREPORT_ITEMSIZE;
collisionreport[b]=_objects_ammo[e.getBody0()];collisionreport[b+1]=_objects_ammo[e.getBody1()];break}SUPPORT_TRANSFERABLE?transferableMessage(collisionreport.buffer,[collisionreport.buffer]):transferableMessage(collisionreport)};
reportVehicles=function(){var a,b,c,d,e=0,f=0,g=0;SUPPORT_TRANSFERABLE&&vehiclereport.length<2+_num_wheels*VEHICLEREPORT_ITEMSIZE&&(vehiclereport=new Float32Array(2+Math.ceil(_num_wheels/REPORT_CHUNKSIZE)*REPORT_CHUNKSIZE*VEHICLEREPORT_ITEMSIZE),vehiclereport[0]=MESSAGE_TYPES.VEHICLEREPORT);for(a in _vehicles)if(_vehicles.hasOwnProperty(a))for(b=_vehicles[a],g=0;g<b.getNumWheels();g++)c=b.getWheelInfo(g).get_m_worldTransform(),d=c.getOrigin(),c=c.getRotation(),e=1+f++*VEHICLEREPORT_ITEMSIZE,vehiclereport[e]=
a,vehiclereport[e+1]=g,vehiclereport[e+2]=d.x(),vehiclereport[e+3]=d.y(),vehiclereport[e+4]=d.z(),vehiclereport[e+5]=c.x(),vehiclereport[e+6]=c.y(),vehiclereport[e+7]=c.z(),vehiclereport[e+8]=c.w();0!==g&&(SUPPORT_TRANSFERABLE?transferableMessage(vehiclereport.buffer,[vehiclereport.buffer]):transferableMessage(vehiclereport))};
reportConstraints=function(){var a,b,c,d,e=0,f=0;SUPPORT_TRANSFERABLE&&constraintreport.length<2+_num_constraints*CONSTRAINTREPORT_ITEMSIZE&&(constraintreport=new Float32Array(2+Math.ceil(_num_constraints/REPORT_CHUNKSIZE)*REPORT_CHUNKSIZE*CONSTRAINTREPORT_ITEMSIZE),constraintreport[0]=MESSAGE_TYPES.CONSTRAINTREPORT);for(a in _constraints)_constraints.hasOwnProperty(a)&&(b=_constraints[a],c=b.getRigidBodyA(),d=b.getFrameOffsetA(),d=d.getOrigin(),e=1+f++*CONSTRAINTREPORT_ITEMSIZE,constraintreport[e]=
a,constraintreport[e+1]=c.id,constraintreport[e+2]=d.getX(),constraintreport[e+3]=d.getY(),constraintreport[e+4]=d.getZ(),constraintreport[e+5]=b.getAppliedImpulse());0!==f&&(SUPPORT_TRANSFERABLE?transferableMessage(constraintreport.buffer,[constraintreport.buffer]):transferableMessage(constraintreport))};
self.onmessage=function(a){if(a.data instanceof Float32Array)switch(a.data[0]){case MESSAGE_TYPES.WORLDREPORT:worldreport=new Float32Array(a.data);break;case MESSAGE_TYPES.COLLISIONREPORT:collisionreport=new Float32Array(a.data);break;case MESSAGE_TYPES.VEHICLEREPORT:vehiclereport=new Float32Array(a.data);break;case MESSAGE_TYPES.CONSTRAINTREPORT:constraintreport=new Float32Array(a.data)}else if(a.data.cmd&&public_functions[a.data.cmd])public_functions[a.data.cmd](a.data.params)};
